### ISSUE TITLE
cannot convert from 'Unity.AspNet.Mvc.PerRequestLifetimeManager' to 'Unity.Injection.InjectionMember'

### ISSUE THREAD

**Issue by neozhu** [unitycontainer/aspnet-mvc#10]
container.RegisterType<IUnitOfWorkAsync, UnitOfWork>(new PerRequestLifetimeManager(), null);
container.RegisterType<DbContext, StoreContext>(new PerRequestLifetimeManager(), null);

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'Unity.AspNet.Mvc.PerRequestLifetimeManager' to 'Unity.Injection.InjectionMember'	WebApp	D:\tfsonline\opensource\SmartCode-Engine\CustomBasicScaffolder\Demo\WebApp\App_Start\Mvc.UnityConfig.cs	78	N/A

**Comment by ENikS** [comment]
Did you try: ``RegisterType<IUnitOfWorkAsync, UnitOfWork>(new PerRequestLifetimeManager());``

**Comment by neozhu** [comment]
container.RegisterType<IUnitOfWorkAsync, UnitOfWork>(new PerRequestLifetimeManager());
container.RegisterType<DbContext, StoreContext>(new PerRequestLifetimeManager());
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'Unity.AspNet.Mvc.PerRequestLifetimeManager' to 'Unity.Injection.InjectionMember'	WebApp	D:\tfsonline\opensource\SmartCode-Engine\CustomBasicScaffolder\Demo\WebApp\App_Start\Mvc.UnityConfig.cs	78	N/A
Upgrade last ver 5.9 error

**Comment by neozhu** [comment]
last version 5.9 not Implement LifetimeManager  extend methods
```
for Unity.Abstractions, Version=3.3.1  
 public static IUnityContainer RegisterType<TFrom, TTo>(this IUnityContainer container, LifetimeManager lifetimeManager, params InjectionMember[] injectionMembers) where TTo : TFrom;


```
Unity.Abstractions, Version=4.0.0 removed about LifetimeManager parameter methods

how to fix it?

**Comment by neozhu** [comment]
```
 public class PerRequestLifetimeManager : LifetimeManager,ITypeLifetimeManager
    {
        private readonly object _lifetimeKey = new object();

        /// <summary>
        /// Retrieves a value from the backing store associated with this lifetime policy.
        /// </summary>
        /// <returns>The desired object, or null if no such object is currently stored.</returns>
        public override object GetValue(ILifetimeContainer container = null)
        {
            return UnityPerRequestHttpModule.GetValue(_lifetimeKey);
        }

        /// <summary>
        /// Stores the given value into the backing store for retrieval later.
        /// </summary>
        /// <param name="newValue">The object being stored.</param>
        /// <param name="container"></param>
        public override void SetValue(object newValue, ILifetimeContainer container = null)
        {
            UnityPerRequestHttpModule.SetValue(_lifetimeKey, newValue);
        }

        /// <summary>
        /// Removes the given object from the backing store.
        /// </summary>
        public override void RemoveValue(ILifetimeContainer container = null)
        {
            var disposable = GetValue() as IDisposable;

            disposable?.Dispose();

            UnityPerRequestHttpModule.SetValue(_lifetimeKey, null);
        }

        /// <summary>
        /// Creates clone
        /// </summary>
        /// <returns></returns>
        protected override LifetimeManager OnCreateLifetimeManager()
        {
            return new PerRequestLifetimeManager();
        }
    }
```
I change  PerRequestLifetimeManager  Inherit ITypeLifetimeManager fix it
