### ISSUE TITLE
Introduced NoValue broke PerRequest strategy

### ISSUE THREAD

**Issue by nefremov** [unitycontainer/aspnet-mvc#14]
Hi,
I don't know why I can't make pull request with 403 errcode. But to fix the issue, please, just modify UnityPerRequestHttpModule.GetValue's common return value from null to LifetimeManager.NoValue.

**Comment by ENikS** [comment]
You need to fork the repo, and create a pull request from your fork.

**Comment by nefremov** [comment]
Thank you. [#15](https://github.com/unitycontainer/aspnet-mvc/pull/15) pull request is proposed

**Comment by ENikS** [comment]
Released
