### ISSUE TITLE
Please upload PDB files for Unity.Mvc.dll on the Microsoft symbol server

### ISSUE THREAD

**Issue by ghost** [unitycontainer/aspnet-mvc#9]
I need the debug symbols for `Unity.Mvc.dll` version 5.0.15 targeting .NET Framework version 4.5.2.

I have set up my Visual Studio Community 2017 version 15.9.2 environment correctly but it doesn't download the PDB's for this specific DLL.

**Comment by ENikS** [comment]
You could download or clone source files for the project and when VS asks for the *.cs file just point it to appropriate path. 

At the moment I am not able to spend any time on creating automated setup to download it to symbol server. But if you want to help and do it yourself and send me a pull request with config changes I'll be happy to add it to the project.

**Comment by MagicAndre1981** [comment]
better approach is to [implement SourceLink and add the PDBs to the NuGet package](https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html)

**Comment by ENikS** [comment]
@MagicAndre1981 Would you like to help with that?

**Comment by MagicAndre1981** [comment]
@ENikS I never used your libs. I only saw the question on stackoverflow.com and suggested him to ask here for support. 

The blogpost shows the steps.

**Comment by MagicAndre1981** [comment]
@ENikS 

I've added it for your small lib to show you how it works:

https://github.com/ENikS/ObservableCollectionEx/pull/4

**Comment by ENikS** [comment]
[Done](https://github.com/unitycontainer/container/blob/da2c9f18051863ac1f0de67b1606d28b38afd3b5/src/Unity.Container.csproj#L80-L93) 

@MagicAndre1981 Thank you for the sample and explanation.

**Comment by ghost** [comment]
Thank you, @MagicAndre1981  and @ENikS.

**Comment by MagicAndre1981** [comment]
ok, hope this helps you @Sathyaish when next version gets released.
